modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/ItemPhysicLite/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="itemphysiclite"
    logoFile="itemphysiclite.png"
    version="1.6.3"
    displayName="ItemPhysicLite"
    displayURL="https://modrinth.com/mod/itemphysic-lite"
    authors="CreativeMD"
    description='''Enhances the rendering of items.'''

[[dependencies.itemphysiclite]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysiclite]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysiclite]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="[2.10.22,)"

[[mixins]]
   config="itemphysiclite.mixins.json"

