modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/CreativeMD/ItemPhysicLite/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="itemphysiclite"
    logoFile="itemphysiclite.png"
    version="1.6.11"
    displayName="ItemPhysicLite"
    displayURL="https://modrinth.com/mod/itemphysic-lite"
    authors="CreativeMD"
    description='''Enhances the rendering of items.'''
    displayTest="NONE"

[[dependencies.itemphysiclite]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.10-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysiclite]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemphysiclite]]
   modId="creativecore"
   type="required"
   ordering="NONE"
   side="BOTH"
   versionRange="[2.14.0,)"

[[mixins]]
   config="itemphysiclite.mixins.json"

